server:
  port: 8080

spring:
  datasource:
    username: root
    password: Test1891@
    url: jdbc:mysql://localhost:3306/search_engine?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
indexing-settings:
  sites:
      - url: https://www.svetlovka.ru
        name: Светловка
      - url: http://www.playback.ru
        name: PlayBack.ru
  userAgent: SuperSearchBot
  referrer: https://www.google.com